// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/grpc/pb/live.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{0}
}

type LiveEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LiveEvent_Danmu
	//	*LiveEvent_Popularity
	//	*LiveEvent_Gift
	//	*LiveEvent_SysMsg
	//	*LiveEvent_Error
	//	*LiveEvent_SuperChat
	//	*LiveEvent_Interaction
	Payload       isLiveEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveEvent) Reset() {
	*x = LiveEvent{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveEvent) ProtoMessage() {}

func (x *LiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveEvent.ProtoReflect.Descriptor instead.
func (*LiveEvent) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{1}
}

func (x *LiveEvent) GetPayload() isLiveEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LiveEvent) GetDanmu() *DanmuMsg {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_Danmu); ok {
			return x.Danmu
		}
	}
	return nil
}

func (x *LiveEvent) GetPopularity() *PopularityMsg {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_Popularity); ok {
			return x.Popularity
		}
	}
	return nil
}

func (x *LiveEvent) GetGift() *GiftData {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_Gift); ok {
			return x.Gift
		}
	}
	return nil
}

func (x *LiveEvent) GetSysMsg() string {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_SysMsg); ok {
			return x.SysMsg
		}
	}
	return ""
}

func (x *LiveEvent) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *LiveEvent) GetSuperChat() *SuperChatMsg {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_SuperChat); ok {
			return x.SuperChat
		}
	}
	return nil
}

func (x *LiveEvent) GetInteraction() *InteractMsg {
	if x != nil {
		if x, ok := x.Payload.(*LiveEvent_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

type isLiveEvent_Payload interface {
	isLiveEvent_Payload()
}

type LiveEvent_Danmu struct {
	Danmu *DanmuMsg `protobuf:"bytes,1,opt,name=danmu,proto3,oneof"`
}

type LiveEvent_Popularity struct {
	Popularity *PopularityMsg `protobuf:"bytes,2,opt,name=popularity,proto3,oneof"`
}

type LiveEvent_Gift struct {
	Gift *GiftData `protobuf:"bytes,3,opt,name=gift,proto3,oneof"`
}

type LiveEvent_SysMsg struct {
	SysMsg string `protobuf:"bytes,4,opt,name=sys_msg,json=sysMsg,proto3,oneof"`
}

type LiveEvent_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type LiveEvent_SuperChat struct {
	SuperChat *SuperChatMsg `protobuf:"bytes,6,opt,name=super_chat,json=superChat,proto3,oneof"`
}

type LiveEvent_Interaction struct {
	Interaction *InteractMsg `protobuf:"bytes,7,opt,name=interaction,proto3,oneof"`
}

func (*LiveEvent_Danmu) isLiveEvent_Payload() {}

func (*LiveEvent_Popularity) isLiveEvent_Payload() {}

func (*LiveEvent_Gift) isLiveEvent_Payload() {}

func (*LiveEvent_SysMsg) isLiveEvent_Payload() {}

func (*LiveEvent_Error) isLiveEvent_Payload() {}

func (*LiveEvent_SuperChat) isLiveEvent_Payload() {}

func (*LiveEvent_Interaction) isLiveEvent_Payload() {}

type DanmuMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	MedalName     string                 `protobuf:"bytes,4,opt,name=medal_name,json=medalName,proto3" json:"medal_name,omitempty"`
	MedalLevel    int32                  `protobuf:"varint,5,opt,name=medal_level,json=medalLevel,proto3" json:"medal_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmuMsg) Reset() {
	*x = DanmuMsg{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmuMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmuMsg) ProtoMessage() {}

func (x *DanmuMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmuMsg.ProtoReflect.Descriptor instead.
func (*DanmuMsg) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{2}
}

func (x *DanmuMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DanmuMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DanmuMsg) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *DanmuMsg) GetMedalName() string {
	if x != nil {
		return x.MedalName
	}
	return ""
}

func (x *DanmuMsg) GetMedalLevel() int32 {
	if x != nil {
		return x.MedalLevel
	}
	return 0
}

type PopularityMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Popularity    int32                  `protobuf:"varint,1,opt,name=popularity,proto3" json:"popularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularityMsg) Reset() {
	*x = PopularityMsg{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularityMsg) ProtoMessage() {}

func (x *PopularityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularityMsg.ProtoReflect.Descriptor instead.
func (*PopularityMsg) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{3}
}

func (x *PopularityMsg) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

type GiftData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname          string                 `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Face           string                 `protobuf:"bytes,3,opt,name=face,proto3" json:"face,omitempty"`
	GiftName       string                 `protobuf:"bytes,4,opt,name=gift_name,json=giftName,proto3" json:"gift_name,omitempty"`
	GiftNum        int32                  `protobuf:"varint,5,opt,name=gift_num,json=giftNum,proto3" json:"gift_num,omitempty"`
	Price          float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	ComboTotalCoin int32                  `protobuf:"varint,7,opt,name=combo_total_coin,json=comboTotalCoin,proto3" json:"combo_total_coin,omitempty"`
	TotalCoin      int32                  `protobuf:"varint,8,opt,name=total_coin,json=totalCoin,proto3" json:"total_coin,omitempty"`
	CoinType       string                 `protobuf:"bytes,9,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	Action         string                 `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	GiftInfo       *GiftInfo              `protobuf:"bytes,11,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"`
	MedalInfo      *MedalInfo             `protobuf:"bytes,12,opt,name=medal_info,json=medalInfo,proto3" json:"medal_info,omitempty"`
	ComboSend      *ComboSend             `protobuf:"bytes,13,opt,name=combo_send,json=comboSend,proto3" json:"combo_send,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GiftData) Reset() {
	*x = GiftData{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftData) ProtoMessage() {}

func (x *GiftData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftData.ProtoReflect.Descriptor instead.
func (*GiftData) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{4}
}

func (x *GiftData) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GiftData) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *GiftData) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *GiftData) GetGiftName() string {
	if x != nil {
		return x.GiftName
	}
	return ""
}

func (x *GiftData) GetGiftNum() int32 {
	if x != nil {
		return x.GiftNum
	}
	return 0
}

func (x *GiftData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GiftData) GetComboTotalCoin() int32 {
	if x != nil {
		return x.ComboTotalCoin
	}
	return 0
}

func (x *GiftData) GetTotalCoin() int32 {
	if x != nil {
		return x.TotalCoin
	}
	return 0
}

func (x *GiftData) GetCoinType() string {
	if x != nil {
		return x.CoinType
	}
	return ""
}

func (x *GiftData) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GiftData) GetGiftInfo() *GiftInfo {
	if x != nil {
		return x.GiftInfo
	}
	return nil
}

func (x *GiftData) GetMedalInfo() *MedalInfo {
	if x != nil {
		return x.MedalInfo
	}
	return nil
}

func (x *GiftData) GetComboSend() *ComboSend {
	if x != nil {
		return x.ComboSend
	}
	return nil
}

type GiftInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImgBasic      string                 `protobuf:"bytes,1,opt,name=img_basic,json=imgBasic,proto3" json:"img_basic,omitempty"`
	Gif           string                 `protobuf:"bytes,2,opt,name=gif,proto3" json:"gif,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiftInfo) Reset() {
	*x = GiftInfo{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftInfo) ProtoMessage() {}

func (x *GiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftInfo.ProtoReflect.Descriptor instead.
func (*GiftInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{5}
}

func (x *GiftInfo) GetImgBasic() string {
	if x != nil {
		return x.ImgBasic
	}
	return ""
}

func (x *GiftInfo) GetGif() string {
	if x != nil {
		return x.Gif
	}
	return ""
}

type MedalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedalName     string                 `protobuf:"bytes,1,opt,name=medal_name,json=medalName,proto3" json:"medal_name,omitempty"`
	MedalLevel    int32                  `protobuf:"varint,2,opt,name=medal_level,json=medalLevel,proto3" json:"medal_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedalInfo) Reset() {
	*x = MedalInfo{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalInfo) ProtoMessage() {}

func (x *MedalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalInfo.ProtoReflect.Descriptor instead.
func (*MedalInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{6}
}

func (x *MedalInfo) GetMedalName() string {
	if x != nil {
		return x.MedalName
	}
	return ""
}

func (x *MedalInfo) GetMedalLevel() int32 {
	if x != nil {
		return x.MedalLevel
	}
	return 0
}

type ComboSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComboId       string                 `protobuf:"bytes,1,opt,name=combo_id,json=comboId,proto3" json:"combo_id,omitempty"`
	ComboNum      int32                  `protobuf:"varint,2,opt,name=combo_num,json=comboNum,proto3" json:"combo_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComboSend) Reset() {
	*x = ComboSend{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComboSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComboSend) ProtoMessage() {}

func (x *ComboSend) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComboSend.ProtoReflect.Descriptor instead.
func (*ComboSend) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{7}
}

func (x *ComboSend) GetComboId() string {
	if x != nil {
		return x.ComboId
	}
	return ""
}

func (x *ComboSend) GetComboNum() int32 {
	if x != nil {
		return x.ComboNum
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Face          string                 `protobuf:"bytes,1,opt,name=face,proto3" json:"face,omitempty"`
	Uname         string                 `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *UserInfo) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

type SuperChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedalInfo     *MedalInfo             `protobuf:"bytes,1,opt,name=medal_info,json=medalInfo,proto3" json:"medal_info,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FontColor     string                 `protobuf:"bytes,3,opt,name=font_color,json=fontColor,proto3" json:"font_color,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,5,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuperChatMsg) Reset() {
	*x = SuperChatMsg{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuperChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperChatMsg) ProtoMessage() {}

func (x *SuperChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperChatMsg.ProtoReflect.Descriptor instead.
func (*SuperChatMsg) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{9}
}

func (x *SuperChatMsg) GetMedalInfo() *MedalInfo {
	if x != nil {
		return x.MedalInfo
	}
	return nil
}

func (x *SuperChatMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SuperChatMsg) GetFontColor() string {
	if x != nil {
		return x.FontColor
	}
	return ""
}

func (x *SuperChatMsg) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SuperChatMsg) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *SuperChatMsg) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SuperChatMsg) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type InteractMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractMsg) Reset() {
	*x = InteractMsg{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractMsg) ProtoMessage() {}

func (x *InteractMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractMsg.ProtoReflect.Descriptor instead.
func (*InteractMsg) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{10}
}

func (x *InteractMsg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InteractMsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InteractMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InteractMsg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type InteractData102 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Combo         []*InteractCombo       `protobuf:"bytes,1,rep,name=combo,proto3" json:"combo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractData102) Reset() {
	*x = InteractData102{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractData102) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractData102) ProtoMessage() {}

func (x *InteractData102) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractData102.ProtoReflect.Descriptor instead.
func (*InteractData102) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{11}
}

func (x *InteractData102) GetCombo() []*InteractCombo {
	if x != nil {
		return x.Combo
	}
	return nil
}

type InteractCombo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Cnt           int32                  `protobuf:"varint,4,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Guide         string                 `protobuf:"bytes,5,opt,name=guide,proto3" json:"guide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractCombo) Reset() {
	*x = InteractCombo{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractCombo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractCombo) ProtoMessage() {}

func (x *InteractCombo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractCombo.ProtoReflect.Descriptor instead.
func (*InteractCombo) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{12}
}

func (x *InteractCombo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InteractCombo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InteractCombo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InteractCombo) GetCnt() int32 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *InteractCombo) GetGuide() string {
	if x != nil {
		return x.Guide
	}
	return ""
}

type InteractDataNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cnt           int32                  `protobuf:"varint,1,opt,name=cnt,proto3" json:"cnt,omitempty"`
	SuffixText    string                 `protobuf:"bytes,2,opt,name=suffix_text,json=suffixText,proto3" json:"suffix_text,omitempty"`
	GiftId        int32                  `protobuf:"varint,3,opt,name=gift_id,json=giftId,proto3" json:"gift_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractDataNotice) Reset() {
	*x = InteractDataNotice{}
	mi := &file_api_grpc_pb_live_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractDataNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractDataNotice) ProtoMessage() {}

func (x *InteractDataNotice) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_pb_live_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractDataNotice.ProtoReflect.Descriptor instead.
func (*InteractDataNotice) Descriptor() ([]byte, []int) {
	return file_api_grpc_pb_live_proto_rawDescGZIP(), []int{13}
}

func (x *InteractDataNotice) GetCnt() int32 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *InteractDataNotice) GetSuffixText() string {
	if x != nil {
		return x.SuffixText
	}
	return ""
}

func (x *InteractDataNotice) GetGiftId() int32 {
	if x != nil {
		return x.GiftId
	}
	return 0
}

var File_api_grpc_pb_live_proto protoreflect.FileDescriptor

const file_api_grpc_pb_live_proto_rawDesc = "" +
	"\n" +
	"\x16api/grpc/pb/live.proto\x12\x04live\"\a\n" +
	"\x05Empty\"\xba\x02\n" +
	"\tLiveEvent\x12&\n" +
	"\x05danmu\x18\x01 \x01(\v2\x0e.live.DanmuMsgH\x00R\x05danmu\x125\n" +
	"\n" +
	"popularity\x18\x02 \x01(\v2\x13.live.PopularityMsgH\x00R\n" +
	"popularity\x12$\n" +
	"\x04gift\x18\x03 \x01(\v2\x0e.live.GiftDataH\x00R\x04gift\x12\x19\n" +
	"\asys_msg\x18\x04 \x01(\tH\x00R\x06sysMsg\x12\x16\n" +
	"\x05error\x18\x05 \x01(\tH\x00R\x05error\x123\n" +
	"\n" +
	"super_chat\x18\x06 \x01(\v2\x12.live.SuperChatMsgH\x00R\tsuperChat\x125\n" +
	"\vinteraction\x18\a \x01(\v2\x11.live.InteractMsgH\x00R\vinteractionB\t\n" +
	"\apayload\"\x99\x01\n" +
	"\bDanmuMsg\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"medal_name\x18\x04 \x01(\tR\tmedalName\x12\x1f\n" +
	"\vmedal_level\x18\x05 \x01(\x05R\n" +
	"medalLevel\"/\n" +
	"\rPopularityMsg\x12\x1e\n" +
	"\n" +
	"popularity\x18\x01 \x01(\x05R\n" +
	"popularity\"\x9f\x03\n" +
	"\bGiftData\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05uname\x18\x02 \x01(\tR\x05uname\x12\x12\n" +
	"\x04face\x18\x03 \x01(\tR\x04face\x12\x1b\n" +
	"\tgift_name\x18\x04 \x01(\tR\bgiftName\x12\x19\n" +
	"\bgift_num\x18\x05 \x01(\x05R\agiftNum\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12(\n" +
	"\x10combo_total_coin\x18\a \x01(\x05R\x0ecomboTotalCoin\x12\x1d\n" +
	"\n" +
	"total_coin\x18\b \x01(\x05R\ttotalCoin\x12\x1b\n" +
	"\tcoin_type\x18\t \x01(\tR\bcoinType\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\tR\x06action\x12+\n" +
	"\tgift_info\x18\v \x01(\v2\x0e.live.GiftInfoR\bgiftInfo\x12.\n" +
	"\n" +
	"medal_info\x18\f \x01(\v2\x0f.live.MedalInfoR\tmedalInfo\x12.\n" +
	"\n" +
	"combo_send\x18\r \x01(\v2\x0f.live.ComboSendR\tcomboSend\"9\n" +
	"\bGiftInfo\x12\x1b\n" +
	"\timg_basic\x18\x01 \x01(\tR\bimgBasic\x12\x10\n" +
	"\x03gif\x18\x02 \x01(\tR\x03gif\"K\n" +
	"\tMedalInfo\x12\x1d\n" +
	"\n" +
	"medal_name\x18\x01 \x01(\tR\tmedalName\x12\x1f\n" +
	"\vmedal_level\x18\x02 \x01(\x05R\n" +
	"medalLevel\"C\n" +
	"\tComboSend\x12\x19\n" +
	"\bcombo_id\x18\x01 \x01(\tR\acomboId\x12\x1b\n" +
	"\tcombo_num\x18\x02 \x01(\x05R\bcomboNum\"4\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04face\x18\x01 \x01(\tR\x04face\x12\x14\n" +
	"\x05uname\x18\x02 \x01(\tR\x05uname\"\xf4\x01\n" +
	"\fSuperChatMsg\x12.\n" +
	"\n" +
	"medal_info\x18\x01 \x01(\v2\x0f.live.MedalInfoR\tmedalInfo\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"font_color\x18\x03 \x01(\tR\tfontColor\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12+\n" +
	"\tuser_info\x18\x05 \x01(\v2\x0e.live.UserInfoR\buserInfo\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\"]\n" +
	"\vInteractMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"<\n" +
	"\x0fInteractData102\x12)\n" +
	"\x05combo\x18\x01 \x03(\v2\x13.live.InteractComboR\x05combo\"y\n" +
	"\rInteractCombo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x10\n" +
	"\x03cnt\x18\x04 \x01(\x05R\x03cnt\x12\x14\n" +
	"\x05guide\x18\x05 \x01(\tR\x05guide\"`\n" +
	"\x12InteractDataNotice\x12\x10\n" +
	"\x03cnt\x18\x01 \x01(\x05R\x03cnt\x12\x1f\n" +
	"\vsuffix_text\x18\x02 \x01(\tR\n" +
	"suffixText\x12\x17\n" +
	"\agift_id\x18\x03 \x01(\x05R\x06giftId2:\n" +
	"\vLiveService\x12+\n" +
	"\tSubscribe\x12\v.live.Empty\x1a\x0f.live.LiveEvent0\x01B#Z!uooobarry/yuuna-danmu/api/grpc/pbb\x06proto3"

var (
	file_api_grpc_pb_live_proto_rawDescOnce sync.Once
	file_api_grpc_pb_live_proto_rawDescData []byte
)

func file_api_grpc_pb_live_proto_rawDescGZIP() []byte {
	file_api_grpc_pb_live_proto_rawDescOnce.Do(func() {
		file_api_grpc_pb_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_pb_live_proto_rawDesc), len(file_api_grpc_pb_live_proto_rawDesc)))
	})
	return file_api_grpc_pb_live_proto_rawDescData
}

var file_api_grpc_pb_live_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_grpc_pb_live_proto_goTypes = []any{
	(*Empty)(nil),              // 0: live.Empty
	(*LiveEvent)(nil),          // 1: live.LiveEvent
	(*DanmuMsg)(nil),           // 2: live.DanmuMsg
	(*PopularityMsg)(nil),      // 3: live.PopularityMsg
	(*GiftData)(nil),           // 4: live.GiftData
	(*GiftInfo)(nil),           // 5: live.GiftInfo
	(*MedalInfo)(nil),          // 6: live.MedalInfo
	(*ComboSend)(nil),          // 7: live.ComboSend
	(*UserInfo)(nil),           // 8: live.UserInfo
	(*SuperChatMsg)(nil),       // 9: live.SuperChatMsg
	(*InteractMsg)(nil),        // 10: live.InteractMsg
	(*InteractData102)(nil),    // 11: live.InteractData102
	(*InteractCombo)(nil),      // 12: live.InteractCombo
	(*InteractDataNotice)(nil), // 13: live.InteractDataNotice
}
var file_api_grpc_pb_live_proto_depIdxs = []int32{
	2,  // 0: live.LiveEvent.danmu:type_name -> live.DanmuMsg
	3,  // 1: live.LiveEvent.popularity:type_name -> live.PopularityMsg
	4,  // 2: live.LiveEvent.gift:type_name -> live.GiftData
	9,  // 3: live.LiveEvent.super_chat:type_name -> live.SuperChatMsg
	10, // 4: live.LiveEvent.interaction:type_name -> live.InteractMsg
	5,  // 5: live.GiftData.gift_info:type_name -> live.GiftInfo
	6,  // 6: live.GiftData.medal_info:type_name -> live.MedalInfo
	7,  // 7: live.GiftData.combo_send:type_name -> live.ComboSend
	6,  // 8: live.SuperChatMsg.medal_info:type_name -> live.MedalInfo
	8,  // 9: live.SuperChatMsg.user_info:type_name -> live.UserInfo
	12, // 10: live.InteractData102.combo:type_name -> live.InteractCombo
	0,  // 11: live.LiveService.Subscribe:input_type -> live.Empty
	1,  // 12: live.LiveService.Subscribe:output_type -> live.LiveEvent
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_grpc_pb_live_proto_init() }
func file_api_grpc_pb_live_proto_init() {
	if File_api_grpc_pb_live_proto != nil {
		return
	}
	file_api_grpc_pb_live_proto_msgTypes[1].OneofWrappers = []any{
		(*LiveEvent_Danmu)(nil),
		(*LiveEvent_Popularity)(nil),
		(*LiveEvent_Gift)(nil),
		(*LiveEvent_SysMsg)(nil),
		(*LiveEvent_Error)(nil),
		(*LiveEvent_SuperChat)(nil),
		(*LiveEvent_Interaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_pb_live_proto_rawDesc), len(file_api_grpc_pb_live_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_pb_live_proto_goTypes,
		DependencyIndexes: file_api_grpc_pb_live_proto_depIdxs,
		MessageInfos:      file_api_grpc_pb_live_proto_msgTypes,
	}.Build()
	File_api_grpc_pb_live_proto = out.File
	file_api_grpc_pb_live_proto_goTypes = nil
	file_api_grpc_pb_live_proto_depIdxs = nil
}
